In [23]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

Requirement already satisfied: numpy in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (2.4.4)
Requirement already satisfied: pandas in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from seaborn) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [25]:
df=pd.read_csv("data/stud.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [26]:
df.shape

(1000, 8)

In [27]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [30]:
df.nunique().sum()

np.int64(247)

In [31]:
df.describe()
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [32]:
print(f"Categories in 'gender' variable: {df["gender"].unique()}")
print(f"Categories in 'race/ethnicity' variable: {df["race/ethnicity"].unique()}")
print(f"Categories in 'parental level of education' variable: {df["parental level of education"].unique()}")
print(f"Categories in 'lunch' variable: {df["lunch"].unique()}")
print(f"Categories in 'test preparation course' variable: {df["test preparation course"].unique()}")

Categories in 'gender' variable: <StringArray>
['female', 'male']
Length: 2, dtype: str
Categories in 'race/ethnicity' variable: <StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
Categories in 'parental level of education' variable: <StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
Categories in 'lunch' variable: <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
Categories in 'test preparation course' variable: <StringArray>
['none', 'completed']
Length: 2, dtype: str

In [33]:
#print columns
numeric_features = df.select_dtypes(include=['number']).columns
categorical_features = df.select_dtypes(include=['object', 'category']).columns

print("Numerical:", numeric_features)
print("Categorical:", categorical_features)

Numerical: Index(['math score', 'reading score', 'writing score'], dtype='str')
Categorical: Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='str')

In [34]:
df["total score"]=df['math score']+df['reading score']+df['writing score']
df["average"]=df["total score"]/3
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [35]:
reading_full = df[df['reading score'] == 100]['average'].count()
writing_full = df[df['writing score'] == 100]['average'].count()
math_full = df[df['math score'] == 100]['average'].count()

print(f'Number of students with full marks in Maths: {math_full}')
print(f'Number of students with full marks in Writing: {writing_full}')
print(f'Number of students with full marks in Reading: {reading_full}')

Number of students with full marks in Maths: 7
Number of students with full marks in Writing: 14
Number of students with full marks in Reading: 17

In [38]:
reading_less_20 = df[df['reading score'] <= 20]['average'].count()
writing_less_20 = df[df['writing score'] <= 20]['average'].count()
math_less_20 = df[df['math score'] <= 20]['average'].count()

print(f'Number of students with less than 20 marks in Maths: {math_less_20}')
print(f'Number of students with less than 20 marks in Writing: {writing_less_20}')
print(f'Number of students with less than 20 marks in Reading: {reading_less_20}')

Number of students with less than 20 marks in Maths: 4
Number of students with less than 20 marks in Writing: 3
Number of students with less than 20 marks in Reading: 1