In [1]:
!pip install scikit-learn
!pip install catboost
!pip install xgboost

Requirement already satisfied: scikit-learn in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: catboost in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (1.2.10)
Requirement already satisfied: graphviz in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (3.10.9)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (2.4.4)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (3.0.2)
Requirement already satisfied: scipy in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (1.17.1)
Requirement already satisfied: plotly in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from plotly->catboost) (2.20.0)
Requirement already satisfied: xgboost in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (3.2.0)
Requirement already satisfied: numpy in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in /Users/arpitpatel/Desktop/mlproject/venv/lib/python3.13/site-packages (from xgboost) (1.17.1)

In [18]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Modelling

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('/Users/arpitpatel/Desktop/mlproject/notebook/data/stud.csv')

In [4]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [9]:
X=df.drop(['math score'],axis=1)

In [11]:
y=df["math score"]

In [15]:
#Create column transformer with three types of transformer
num_features=X.select_dtypes(exclude='object').columns
cat_features=X.select_dtypes(include='object').columns

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numeric_transformer,num_features)
    ]
)

In [16]:
X=preprocessor.fit_transform(X)

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)
X_train.shape, X_test.shape

((800, 19), (200, 19))

In [25]:
def evaluate_model (true, predicted):
    mae=mean_absolute_error(true, predicted)
    mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square=r2_score (true, predicted)
    return mae, rmse, r2_square

In [30]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(),
    "CatBoosting Regressor": CatBoostRegressor (verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred=model.predict(X_train)
    y_test_pred = model.predict(X_test)

# Evaluate Train and Test dataset
    model_train_mae,model_train_rmse,model_train_r2=evaluate_model(y_train, y_train_pred)
    model_test_mae,model_test_rmse,model_test_r2=evaluate_model(y_test, y_test_pred)


    print(list(models.keys()) [1])
    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('-'*35)

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)

    print('='*40)
    print('\n')

Lasso
Model performance for Training set
- Root Mean Squared Error: 5.3231
- Mean Absolute Error: 4.2667
- R2 Score: 0.8743
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3940
- Mean Absolute Error: 4.2148
- R2 Score: 0.8804
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 6.5938
- Mean Absolute Error: 5.2063
- R2 Score: 0.8071
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.5197
- Mean Absolute Error: 5.1579
- R2 Score: 0.8253
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 5.3233
- Mean Absolute Error: 4.2650
- R2 Score: 0.8743
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3904
- Mean Absolute Error: 4.2111
- R2 Score: 0.8806
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 5.7172
- Mean Absolute Error: 4.5270
- R2 Score: 0.8550
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.2553
- Mean Absolute Error: 5.6280
- R2 Score: 0.7837
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 0.2795
- Mean Absolute Error: 0.0187
- R2 Score: 0.9997
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.9699
- Mean Absolute Error: 6.3900
- R2 Score: 0.7390
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 2.2760
- Mean Absolute Error: 1.8237
- R2 Score: 0.9770
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0599
- Mean Absolute Error: 4.7093
- R2 Score: 0.8491
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 1.0073
- Mean Absolute Error: 0.6875
- R2 Score: 0.9955
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.4733
- Mean Absolute Error: 5.0577
- R2 Score: 0.8278
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 3.0427
- Mean Absolute Error: 2.4054
- R2 Score: 0.9589
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0086
- Mean Absolute Error: 4.6125
- R2 Score: 0.8516
========================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 5.8493
- Mean Absolute Error: 4.8132
- R2 Score: 0.8482
-----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.1617
- Mean Absolute Error: 4.7834
- R2 Score: 0.8440
========================================

In [31]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"], ascending=False)

                Model Name  R2_Score
2                    Ridge  0.880593
0        Linear Regression  0.880433
7    CatBoosting Regressor  0.851632
5  Random Forest Regressor  0.849088
8       AdaBoost Regressor  0.843975
6             XGBRegressor  0.827797
1                    Lasso  0.825320
3    K-Neighbors Regressor  0.783681
4            Decision Tree  0.738964

In [32]:
#Linear Regression
lin_model = LinearRegression(fit_intercept=True)
lin_model = lin_model.fit(X_train, y_train)
y_pred = lin_model.predict(X_test)
score = r2_score(y_test, y_pred) *100
print(" Accuracy of the model is %.2f" %score)

 Accuracy of the model is 88.04

In [34]:
#Difference between actual and presicted value
pred_df=pd.DataFrame({'Actual Value':y_test, 'Predicted Value':y_pred, 'Difference':y_test-y_pred})
pred_df

     Actual Value  Predicted Value  Difference
521            91        76.387970   14.612030
737            53        58.885970   -5.885970
740            80        76.990265    3.009735
660            74        76.851804   -2.851804
411            84        87.627378   -3.627378
..            ...              ...         ...
408            52        43.409149    8.590851
332            62        62.152214   -0.152214
208            74        67.888395    6.111605
613            65        67.022287   -2.022287
78             61        62.345132   -1.345132

[200 rows x 3 columns]